### ISSUE TITLE
Mention coqffi in the `Related' section of the README.md

### ISSUE THREAD

**Issue by lthms** [Lysxia/coq-simple-io#22]
[`coqffi`](https://github.com/coq-community/coqffi) is using `coq-simple-io` in order to model and support OCaml impure functions. I believe `coqffi` can be seen as a complementary tool to be used to more easily benefit from the `IO` monad of `coq-simple-io`, and it would make sense to mention it in the README.

What do you think?

**Comment by Lysxia** [comment]
Just fixed in 770d156
