### ISSUE TITLE
Bring back the MonadFix instance in a separate module

### ISSUE THREAD

**Issue by lthms** [Lysxia/coq-simple-io#24]
Hi @Lysxia 

I saw that in the latest release of `coq-simple-io`, the `MonadFix` instance has been removed, due to the universe inconsistencies is was provoking.

However, I often use `MonadFix` and `IO` in the same projects (*e.g.*, in projects like [my echo server in Coq](https://soap.coffee/~lthms/posts/CoqffiEcho.html)), and therefore have to redefine it each time.

I was wondering wether or not it would be an acceptable middle-ground solution to add this instance in `coq-simple-io` again, but this time in a different module, with the according warning/documentation on the issue it has?

**Comment by Lysxia** [comment]
Sure, that sounds like a good idea!

**Comment by lthms** [comment]
:fireworks: thanks!
