### ISSUE TITLE
Tag for Coq 8.13

### ISSUE THREAD

**Issue by gares** [Lysxia/coq-simple-io#26]
We are currently testing commit 770d156e05be73419cdd83d0e29de8d6e1d11f5c for the coq-platform release for Coq 8.13.
Would you mind tagging this commit or any other one which works for Coq's branch v8.13?

**Comment by Lysxia** [comment]
Sure. I tagged 1.5.0 and made a PR to opam-coq-archive.

**Comment by gares** [comment]
thanks!
