### ISSUE TITLE
Sample command

### ISSUE THREAD

**Issue by liyishuai** [Lysxia/coq-simple-io#27]
In QuickChick there's a [Sample](https://github.com/QuickChick/QuickChick/blob/04c1d5fbff95eb462bcf2a1ab8393a5222150317/QuickChickInterface.v#L665-L674) command for G monad. Is it worth adding a sampler for IO as well?

**Comment by Lysxia** [comment]
That would be nice indeed. I think you could just call it `RunIO`.

**Comment by Lysxia** [comment]
See the branch `run-io`, though I'd like to refactor and minimize it before merging it.

**Comment by liyishuai** [comment]
I've updated the test suite to include this usage. The main pending fix is the "QuickChick" phrasing.

**Comment by Lysxia** [comment]
Closed by #28
