### ISSUE TITLE
Throw exceptions with messages

### ISSUE THREAD

**Issue by liyishuai** [Lysxia/coq-simple-io#30]
https://github.com/Lysxia/coq-simple-io/blob/f7536c629dd02883abb5a2d64865becafed3af5b/src/IO_Exceptions.v#L18-L23

Is it worth changing `IO (option a)` to `IO (string + a)`? This would involve choosing an extraction for `sum`.

**Comment by liyishuai** [comment]
Seems available since 4.03: https://github.com/ocaml/ocaml/commit/19a5d5eb50fa5c5661a33343cded8ec1442703be. Maybe worth adding to Coq.

**Comment by Lysxia** [comment]
Oh I see it's the `Result` module that came later.

**Comment by Lysxia** [comment]
- I think if you catch the `Invalid_arg` exception at all, you can usually provide a better string for the context.
- Not extracting `sum` to `result` is the less surprising choice and I don't see much benefit in avoiding the duplication.
