### ISSUE TITLE
Documentation on GH pages

### ISSUE THREAD

**Issue by Lysxia** [Lysxia/coq-simple-io#4]

**Comment by liyishuai** [comment]
I'm starting to forget the interfaces, and online documentations would be useful.

**Comment by Lysxia** [comment]
Like this? https://lysxia.github.io/coq-simple-io/toc.html

I'm open to ideas for enhancements.

**Comment by liyishuai** [comment]
Looks good. I'll polish some parts when necessary.

**Comment by liyishuai** [comment]
- `IO.bind` is [indexed under I](https://lysxia.github.io/coq-simple-io/indexpage.html#global_I) rather than B.
- https://lysxia.github.io/coq-simple-io/index.html is not found.

**Comment by Lysxia** [comment]
- Sounds like a Coq bug!
- What should it contain?

**Comment by liyishuai** [comment]
Maybe restructure README and point people to Installation, Documentation, Examples?

**Comment by Lysxia** [comment]
That's what the README is already for.

**Comment by liyishuai** [comment]
I'm proposing README as `index.html`, so as to:
- Avoid switching between repo and GH pages; and
- Eliminate dangling links in GH pages.

**Comment by liyishuai** [comment]
Should we put a link to the documentation somewhere, so that other users than me (if any) needn't search for this issue thread?

**Comment by Lysxia** [comment]
Sure. You can make a PR.

**Comment by liyishuai** [comment]
Maybe worth adding the URL to the right column of the repository info. https://github.com/Lysxia/coq-simple-io/blob/master/README.md#documentation requires scrolling down the README, which I usually forget.

And, time to close this (5-year-old) issue?

**Comment by Lysxia** [comment]
Fine by me. Tell me if you're missing some rights to modify the Github repo page.

**Comment by liyishuai** [comment]
<img width="338" alt="image" src="https://github.com/user-attachments/assets/54e02ed0-7fed-43c3-89ac-8a157afc5210">  
<img width="942" alt="image" src="https://github.com/user-attachments/assets/eb4444e6-1b7f-4452-b100-aa057e313490">

The repo page setting button only appears on my fork (where I'm an admin).

**Comment by Lysxia** [comment]
Ugh, I can't grant admin rights to other people on personal repositories. I updated the sidebar with the link to the docs.
