### ISSUE TITLE
Build fails when V is exported

### ISSUE THREAD

**Issue by LocutusOfBorg** [Lysxia/coq-simple-io#57]
Hello, in Ubuntu builders, verbose mode is enabled by default with 
export V=1

this breaks the build of your tool because it does
```
	$(V)cppo -V COQ:$(COQ_VERSION) -V OCAML:$(OCAML_VERSION) -n -o $@ $^
```
in Makefile, resulting in a call of something like
"1cppo" binary.

Please document the V variable, or remove it if possible (or use a better and longer name?)

thanks

**Comment by Lysxia** [comment]
OK I will remove it.

**Comment by LocutusOfBorg** [comment]
Fixed in https://github.com/Lysxia/coq-simple-io/issues/63

**Comment by LocutusOfBorg** [comment]
I think it was added here https://github.com/Lysxia/coq-simple-io/commit/1ba9d9a483e1f31922bc41bffd8907bc3d6ee85e for no apparent reason?

**Comment by liyishuai** [comment]
The `$(V)` prefix was a naïve way to control the verbosity of build logs (e.g., `make V=@`). Indeed removing for compatibility.

Proposing closing by Tuesday 10 Dec 2024 AoE, since the fix has been merged.

**Comment by LocutusOfBorg** [comment]
thanks!
