### ISSUE TITLE
what is the best version for coq 8.12

### ISSUE THREAD

**Issue by brando90** [Lysxia/coq-simple-io#60]
dev versions always make me unease, what is a better one? 1.5.0 seems to work for now? is it the recommended by the developers?
```
# advice of coq-ext-lib version that might be better than bellow ref:
opam install -y coq-simple-io
#opam install -y coq-simple-io=dev  # dev versions always make me unease
#opam install -y coq-simple-io=1.5.0  # this seemed to work but it says it downgraded, for now leave as is
```

**Comment by Lysxia** [comment]
To summarize what I've mentioned elsewhere:

- Use the latest released version
- Don't use `dev` versions (they are not actually released versions)

Remove the `coq-extra-dev` repository from your opam configuration. Then use whatever version gets picked by `opam install coq-simple-io`.
