### ISSUE TITLE
Non-terminating `read_line` from the command line

### ISSUE THREAD

**Issue by zacque0** [Lysxia/coq-simple-io#76]
Hi, I'm trying to read string from the shell's `stdin`, but I couldn't terminate the reading operation.

### Operation
With the following file `stdin.v` and running it with `coqc stdin.v`, 
```coq
From SimpleIO Require Import SimpleIO.
From Coq Require Import String.
#[local] Open Scope string_scope.

RunIO read_line.
```
I couldn't terminate the reading operation with `Return` or `Ctrl+D` key. Only `Ctrl+C` is recognised, but it interrupts the entire process instead.

![coq-stdin](https://github.com/user-attachments/assets/9de7b3b8-08d1-4c55-8396-81328c172f8c)

### Expected
Since it is a `read_line` operation, I'd expect it to finish reading upon hitting the `Return` key.

Since this is based on OCaml stdlib, its `read_line ()` works fine for me.
![ocaml-readline](https://github.com/user-attachments/assets/801849da-73f1-4d9f-813b-b47727224f92)

Is there a way to read from string stdin from within Gallina?

### Environment
`coqc -v`: 8.20.0
`ocaml --version`: 5.2.1
`opam show coq-simple-io`: 1.10.0
Debian 12 on x86_64 machine

**Comment by liyishuai** [comment]
I don't think `RunIO` was designed with standard input in mind---it's mainly for debug purposes. Please consider extracting and compiling the program manually, see:
https://github.com/Lysxia/coq-simple-io/blob/de32ccf5410dab54daeffafe92c8f69c45089970/test/example/main.v#L35-L43

**Comment by zacque0** [comment]
Ah, no wonder. But it's okay, I can generate a Coq file for normal `coqc`/`coqtop` execution.

> Please consider extracting and compiling the program manually

I don't consider extraction for now. I'd prefer treating Coq as a black box in my scripting environment---string in, string out to other OS processes.

**Comment by Lysxia** [comment]
It might be possible to fix our plugin to forward stdin to the executed extracted program. So I'm reopening this to investigate.
